
import { EvaluationCriteria } from './types';
import { 
  Briefcase, 
  Users, 
  MessageCircle, 
  Lightbulb, 
  TrendingUp, 
  BookOpen, 
  Monitor, 
  Layout, 
  UserCheck, 
  PieChart, 
  CheckSquare 
} from 'lucide-react';

export const EVALUATION_CRITERIA: EvaluationCriteria[] = [
  {
    id: 'c1',
    nameEn: 'Functional Duties Performance',
    nameAr: 'أداء الواجبات الوظيفية',
    description: 'Adherence to official hours, performing classes per schedule, and supervision duties.',
    weight: 10,
    evidenceExamples: 'Attendance log, supervision log, waiting list, curriculum distribution plan (سجل الدوام، سجل المناوبة، خطة توزيع المنهج)',
    icon: Briefcase,
  },
  {
    id: 'c2',
    nameEn: 'Community Interaction',
    nameAr: 'التفاعل مع المجتمع المحلي',
    description: 'Participation in professional learning communities, exchange visits, and workshops.',
    weight: 10,
    evidenceExamples: 'PLC records, visit exchange logs, applied lessons, workshops certificates (سجل مجتمعات التعلم، تبادل الزيارات، الدروس التطبيقية)',
    icon: Users,
  },
  {
    id: 'c3',
    nameEn: 'Parent Interaction',
    nameAr: 'التفاعل مع أولياء الأمور',
    description: 'Communication with parents, providing level updates, and meetings.',
    weight: 10,
    evidenceExamples: 'General assembly photos, meeting minutes, weekly plans sent to parents (صور الجمعية العمومية، تقرير اجتماع، الخطة الأسبوعية)',
    icon: MessageCircle,
  },
  {
    id: 'c4',
    nameEn: 'Teaching Strategies Diversification',
    nameAr: 'التنويع في استراتيجيات التدريس',
    description: 'Using diverse teaching strategies and addressing individual differences.',
    weight: 10,
    evidenceExamples: 'Strategy implementation reports, teacher achievement portfolio (تقرير استراتيجيات، ملف إنجاز المعلم)',
    icon: Lightbulb,
  },
  {
    id: 'c5',
    nameEn: 'Improving Learner Outcomes',
    nameAr: 'تحسين نواتج المتعلمين',
    description: 'Remedial plans for weak students and enrichment for gifted students.',
    weight: 10,
    evidenceExamples: 'Pre/post test results, remedial plans, follow-up sheets (نتائج الاختبارات القبلية والبعدية، خطط علاجية، كشف متابعة)',
    icon: TrendingUp,
  },
  {
    id: 'c6',
    nameEn: 'Curriculum Implementation',
    nameAr: 'إعداد وتنفيذ خطة التعلم',
    description: 'Curriculum distribution, lesson preparation, and homework execution.',
    weight: 10,
    evidenceExamples: 'Distribution plan, lesson preparation, homework samples, tests (خطة توزيع المنهج، إعداد الدروس، نماذج واجبات)',
    icon: BookOpen,
  },
  {
    id: 'c7',
    nameEn: 'Learning Technology',
    nameAr: 'توظيف تقنيات ووسائل التعلم المناسبة',
    description: 'Integrating technology and diversifying educational aids.',
    weight: 10,
    evidenceExamples: 'Photos of aids, software usage reports, smartboard use (صور الوسائل، تقرير برنامج تقني، السبورة الذكية)',
    icon: Monitor,
  },
  {
    id: 'c8',
    nameEn: 'Educational Environment',
    nameAr: 'تهيئة البيئة التعليمية',
    description: 'Addressing student needs, motivation (material/moral), and classroom setup.',
    weight: 5,
    evidenceExamples: 'Classroom classification/layout, motivation forms/awards (تقرير تصنيف الطلاب، نماذج التحفيز)',
    icon: Layout,
  },
  {
    id: 'c9',
    nameEn: 'Classroom Management',
    nameAr: 'الإدارة الصفية',
    description: 'Behavior control, attention management, and attendance tracking.',
    weight: 5,
    evidenceExamples: 'Behavior follow-up sheet, classroom management logs, attendance (كشف المتابعة، تطبيق إدارة الصف، الحضور والغياب)',
    icon: UserCheck,
  },
  {
    id: 'c10',
    nameEn: 'Results Analysis',
    nameAr: 'تحليل نتائج المتعلمين وتشخيص مستوياتهم',
    description: 'Analyzing test results, classifying students, and addressing learning gaps.',
    weight: 10,
    evidenceExamples: 'Results analysis report, learning gap treatment log (تقرير تحليل النتائج، سجل معالجة الفاقد التعليمي)',
    icon: PieChart,
  },
  {
    id: 'c11',
    nameEn: 'Assessment Diversity',
    nameAr: 'تنوع أساليب التقويم',
    description: 'Using paper/electronic tests, projects, and performance tasks.',
    weight: 10,
    evidenceExamples: 'Test samples, student projects, performance tasks (نماذج اختبارات، مشاريع، مهام أدائية)',
    icon: CheckSquare,
  },
];
